Repository MMV-Lab/MSI-Explorer, pull requests merged in 2023-09, with the labels that each got.

#154 fixed layername naming schema
  src/msi_explorer/_analysis.py
  src/msi_explorer/_database.py
  src/msi_explorer/_maldi_ms_data.py
  src/msi_explorer/_metadata.py
  src/msi_explorer/_normalization.py
  src/msi_explorer/_reader.py
  src/msi_explorer/_selection.py
  src/msi_explorer/_spectre_du_roi.py
  src/msi_explorer/_tests/test_maldi_ms_data.py
  src/msi_explorer/_tests/test_metadata.py
  src/msi_explorer/_tests/test_reader.py
  src/msi_explorer/_tests/test_widget.py
  src/msi_explorer/_tests/test_writer.py
  src/msi_explorer/_true_mean_spec.py
  src/msi_explorer/_widget.py
  src/msi_explorer/_writer.py
Labels: bug, enhancement

#156 made checks for x/y pixel count more robust; check for file type is n…
  src/msi_explorer/_maldi_ms_data.py
  src/msi_explorer/_reader.py
  src/msi_explorer/_selection.py
Labels: bug, enhancement

#157 Iss75
  src/msi_explorer/_maldi_ms_data.py
Labels: enhancement

#158 Iss123
  setup.cfg
  src/msi_explorer/_database.py
  src/msi_explorer/_selection.py
  src/msi_explorer/_widget.py
Labels: enhancement

#159 Iss147
  src/msi_explorer/_widget.py
Labels: enhancement

#160 Iss148
  setup.cfg
  src/msi_explorer/__init__.py
  src/msi_explorer/_maldi_ms_data.py
  src/msi_explorer/_selection.py
  src/msi_explorer/_widget.py
Labels: bug, enhancement

#163 Fix fonts
  src/msi_explorer/_selection.py
  src/msi_explorer/fonts/DejaVuSans.ttf
Labels: bug

#165 fixed colorbar and font scaling issues
  src/msi_explorer/_selection.py
Labels: bug, enhancement

#169 charge & adducts now can be taken into account for m/z
  src/msi_explorer/_database.py
  src/msi_explorer/_selection.py
Labels: enhancement

#170 changed description
  README.md
Labels: enhancement

#172 Calculate centroid data
  src/msi_explorer/_maldi_ms_data.py
Labels: enhancement

#173 Iss171
  src/msi_explorer/_maldi_ms_data.py
Labels: enhancement

#174 Fix
  setup.cfg
  src/msi_explorer/__init__.py
  src/msi_explorer/_database.py
  src/msi_explorer/_maldi_ms_data.py
  src/msi_explorer/_selection.py
  src/msi_explorer/_widget.py
  src/msi_explorer/databases/Metabolite_database_ver2.csv
  src/msi_explorer/ressources/placeholder.png
Labels: bug, enhancement
